### ISSUE TITLE
Crash when selecting config

### ISSUE THREAD

**Issue by testcaoy7** [pacien/tincapp#18] opened 2017-08-15 12:16 UTC
My phone runs Android 7.0.

ERROR Report:
```
java.lang.RuntimeException: Unable to start service org.pacien.tincapp.service.TincVpnService@4cb790b with Intent { cmp=org.pacien.tincapp/.service.TincVpnService (has extras) }: org.apache.commons.c.e.a: Could not locate: org.apache.commons.c.g.l@bce80da[fileName=network.conf,basePath=/storage/emulated/0/Android/data/org.pacien.tincapp/files/mesh,sourceURL=,encoding=ISO-8859-1,fileSystem=<null>,locationStrategy=<null>]
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3391)
	at android.app.ActivityThread.-wrap21(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6275)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: org.apache.commons.c.e.a: Could not locate: org.apache.commons.c.g.l@bce80da[fileName=network.conf,basePath=/storage/emulated/0/Android/data/org.pacien.tincapp/files/mesh,sourceURL=,encoding=ISO-8859-1,fileSystem=<null>,locationStrategy=<null>]
	at org.apache.commons.c.g.n.f(Unknown Source)
	at org.apache.commons.c.g.h.b(Unknown Source)
	at org.apache.commons.c.g.h.f(Unknown Source)
	at org.apache.commons.c.b.m.a(Unknown Source)
	at org.apache.commons.c.b.m.a(Unknown Source)
	at org.apache.commons.c.b.m.a(Unknown Source)
	at org.apache.commons.c.b.c.d(Unknown Source)
	at org.apache.commons.c.b.c.c(Unknown Source)
	at org.apache.commons.c.b.a.a.b(Unknown Source)
	at org.pacien.tincapp.a.b$a.a(Unknown Source)
	at org.pacien.tincapp.service.TincVpnService.b(Unknown Source)
	at org.pacien.tincapp.service.TincVpnService.onStartCommand(Unknown Source)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3374)
	... 8 more
```

**Comment by pacien** [comment] 2017-08-15 14:10
```
Could not locate: […] fileName=network.conf,basePath=/storage/emulated/0/Android/data/org.pacien.tincapp/files/mesh […]
```

Seems like the `network.conf` file is missing from the network's configuration directory.
(Better error handling and reporting is planned for future releases.)

**Comment by testcaoy7** [comment] 2017-08-16 02:39
@pacien Does this app require ROOT access?  Or it uses Android VPN API? Also what version of Tinc does it support? I use tinc 1.1 on the server.

**Comment by pacien** [comment] 2017-08-16 09:15
As stated on [the project's website](//tincapp.pacien.org):
- This app does not require root access.
- It indeed uses the Android VPN API.
- It embeds tinc 1.1.

I'm closing this ticket as it is not a bug report or a feature request.
Please refer to the documentation and use the IRC channel for any other question.

**Closed by pacien** 2017-08-16 09:15 UTC

**Comment by testcaoy7** [comment] 2017-08-18 23:30
@pacien 
"basePath=/storage/emulated/0/Android/data/org.pacien.tincapp/files/mesh"
Does it means that the app won't crash if I create a  blank network.conf in the "basePath" ?
