### ISSUE TITLE
Encrypting the keys fails: SecretKeyFactory PBKDF-OpenSSL implementation not found

### ISSUE THREAD

**Issue by nmandery** [pacien/tincapp#38] opened 2018-02-12 07:22 UTC
I encountered an issue with the private key encryption not working on my Android 6 phone. See the screenshot below. The error occurs when an key is about to be encrypted after entering the passphrase and confirming the dialog.

Using the app with non-encrypted keys works nicely.

![encrypt-key-error-message-s](https://user-images.githubusercontent.com/140716/36086312-de431c52-0fcb-11e8-8a1d-558a7aac659a.png)

Looking at the logs I did not find anything too suspicious:

```
2018-02-11 22:26:18 tinc[20175]: tincd UNKNOWN (Sep 10 2017 13:01:09) starting, debug level 0
2018-02-11 22:26:18 tinc[20175]: Warning: insecure file permissions for Ed25519 private key file `/storage/emulated/0/Android/data/org.pacien.tincapp/files/test/ed25519_key.priv'!
2018-02-11 22:26:18 tinc[20175]: Warning: insecure file permissions for RSA private key file `/storage/emulated/0/Android/data/org.pacien.tincapp/files/test/rsa_key.priv'!
2018-02-11 22:26:18 tinc[20175]: fd/40 adapter set up.
2018-02-11 22:26:18 tinc[20175]: Ready
2018-02-11 22:27:05 tinc[20175]: Terminating
```

I wondered about the warnings regarding the file permissions on the keys being the cause for this issue. I tried to revoke the groups read and write permissions on these files using a file manager on my rooted phone, but it seems the filesystem does not support changing file permissions.

Anyways: Thanks for providing this app.

**Comment by nmandery** [comment] 2018-02-12 07:29
I just noticed there was a new release of this app yesterday (0.8). I encountered this issue on 0.7 from fdroid. I will re-test it when the new version is in the repositories.

**Comment by pacien** [comment] 2018-02-12 13:18
Hello,
The "insecure file permission" warnings are expected and are not related to this issue.
I am not able to reproduce this bug on Android 5, 6 and 7 with the latest release (v0.8).
Please reopen this issue if the problem persists after upgrading. I'm closing it for now.

**Closed by pacien** 2018-02-12 13:18 UTC
Labels: bug

**Comment by nmandery** [comment] 2018-02-14 11:42
Hi,
I retested this issue with the latest v0.8 release and it still persists. I suspect it may be specific to my phone and the device is due for an system upgrade anyways. So I think there is not much use of trying to resolve this issue as long as I am the only one experiencing it.

**Comment by nmandery** [comment] 2018-03-05 06:08
Thanks, v0.11 fixes the issue on my device.
