### ISSUE TITLE
No known node after VPN restart 

### ISSUE THREAD

**Issue by hoh** [pacien/tincapp#33] opened 2017-10-24 12:30 UTC
The nodes list disappears after stopping and restarting the network. 

## Steps to reproduce:
 * Setup your Tinc network
 * Start the Tinc App
 * See the names of your network nodes in the "Nodes" section
 * Connect to your network by touching on it in the list
 * Stop the connection by pressing the "square button" in the header
 * Connect to your network by touching on it in the list

Tinc now predends to be running, but does not work. The list of nodes now only contains _no known nodes_.

## Temporary solution:

Force stopping the Tinc App fron the Android Apps settings works to be able to re-connect to the network.

## Platform:

Android 7.1.2
LineageOS 14.1 - October 16, 2017
Nexus 6P angler

**Comment by pacien** [comment] 2018-02-16 17:30
This was caused by a race condition during the daemon startup and shutdown.
This should be fixed with commit ref c359d78 which will be included in the next release (v0.9).

**Closed by pacien** 2018-02-16 17:30 UTC
Labels: bug

**Comment by hoh** [comment] 2018-02-17 11:23
Awesome !
